name: Roy-Test

on:
  workflow_dispatch:
  push:
    branches:
      - roy/test-elliot-deploy-pr
  pull_request:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  REGISTRY: ghcr.io

jobs:
  deploy:
    # Deploy Latest Fuel-Core Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Version: ${{ steps.meta.outputs.version }}"
          echo "FUEL_CORE_TAG=$(echo ${{ steps.meta.outputs.tags }} | cut -d':' -f2)" >> $GITHUB_ENV
          echo "FUEL_CORE_VERSION=$(echo ${{ steps.meta.outputs.version }} )" >> $GITHUB_ENV

      - name: Deploy Fuel-Core Developer Environment
        uses: benc-uk/workflow-dispatch@v1
        # if: github.ref == 'refs/heads/master'
        with:
          workflow: Deploy Fuel-Core on k8s
          repo: FuelLabs/fuel-deployment
          ref: refs/heads/master
          token: ${{ secrets.REPO_TOKEN }}
          inputs: '{ "k8s-type": "${{ env.K8S }}", "config-directory": "${{ env.CONFIG }}", "config-env": "${{ env.ENV }}", "deployment-version": "${{ env.TAG }}", "image-tag": "${{ env.SHA }}", "delete-infra": "${{ env.DELETE_INFRA }}" }'
        env:
          K8S: "eks"
          CONFIG: "fuel-dev1"
          ENV: "fueldevsway.env"
          TAG: ${{ env.FUEL_CORE_TAG }}
          SHA: ${{ env.FUEL_CORE_TAG }}
          DELETE_INFRA: true
